services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started

  db:
    image: postgres
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 30s
      retries: 10
    ports:
      - 5432:5432
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: oetdl-backend
    environment:
      - PORT=4000
    ports:
      - 4000:4000
    depends_on:
      - db
    volumes:
      - ./src:/app/src

volumes:
  pgdata: